
 # Stephen Rhoades G01369048
 # CS 262, Lab section lab214
 # lab2
 
CC = gcc
CFLAGS = -g -Wall -std=c89 -pedantic-errors
LIBS = -lm

all: lab2_srhoade_214.c
	$(CC) lab2_srhoade_214.c -o lab2_srhoade_214 $(CFLAGS) $(LIBS)

clear:
	rm lab2_srhoade_214
 	
