 # Stephen Rhoades G01369048
 # CS 262, Lab section lab214
 # lab4
    
  CC = gcc
  CFLAGS = -g -Wall -std=c89 -pedantic-errors
  TARGET = lab4_srhoade_214
  LIBS = -lm

$(TARGET): $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS) $(LIBS)

clean:
	rm $(TARGET)
